version: '3.8'

services:
  vector-store:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./chroma_data:/chroma
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - vector-store-network
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vector-store-network
    restart: unless-stopped

networks:
  vector-store-network:
    driver: bridge

volumes:
  redis_data: