services:
  vector-store:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/uditkhandelwal/Documents/app_generator/chroma:/chroma
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"  # Expose port 8000 to the host
    restart: unless-stopped